tx-isp-t21-objs := tx_isp_t21_recovered.o \
			  tx_isp_t21_math.o \
			  tx_isp_t21_sinfo.o \
			  tx_isp_t21_exports.o

ifeq ($(CONFIG_VIDEO_V4L2),y)
ifeq ($(CONFIG_DMA_SHARED_BUFFER),y)
tx-isp-t21-objs += tx_isp_t21_v4l2.o
ccflags-y += -DTX_ISP_T21_V4L2
endif
endif

obj-m += tx-isp-t21.o

ccflags-y += -I$(src)/../include
ccflags-y += -DREGTRACE_KERNEL_TREE_BUILD
ccflags-y += -DTX_ISP_T21_SHARED_MATH
ccflags-y += -DTX_ISP_T21_SHARED_SINFO
ccflags-y += -std=gnu99
ccflags-y += -fpermissive
ccflags-y += -Wno-error
ccflags-y += -Wno-error=strict-prototypes
ccflags-y += -Wno-error=implicit-function-declaration
ccflags-y += -Wno-error=implicit-int
ccflags-y += -Wno-error=int-conversion
ccflags-y += -Wno-error=incompatible-pointer-types
