tx-isp-t21-objs := tx_isp_t21_recovered.o \
			  tx_isp_t21_math.o \
			  tx_isp_t21_exports.o
obj-m += tx-isp-t21.o

ccflags-y += -I$(src)/../include
ccflags-y += -DREGTRACE_KERNEL_TREE_BUILD
ccflags-y += -DTX_ISP_T21_SHARED_MATH
ccflags-y += -std=gnu99
ccflags-y += -fpermissive
ccflags-y += -Wno-error
ccflags-y += -Wno-error=strict-prototypes
ccflags-y += -Wno-error=implicit-function-declaration
ccflags-y += -Wno-error=implicit-int
ccflags-y += -Wno-error=int-conversion
ccflags-y += -Wno-error=incompatible-pointer-types
