tx-isp-t40-objs := tx_isp_t40_recovered.o \
		   tx_isp_t40_sinfo.o
obj-m += tx-isp-t40.o

ccflags-y += -I$(src)/../include
ccflags-y += -DREGTRACE_KERNEL_TREE_BUILD
ccflags-y += -O0 -fno-tree-dce -fno-ipa-pure-const -fno-ipa-reference
ccflags-y += -std=gnu99 -w
ccflags-y += -Wno-error=strict-prototypes
ccflags-y += -Wno-error=int-conversion
ccflags-y += -Wno-error=incompatible-pointer-types
ccflags-y += -Wno-error=implicit-function-declaration
