tx-isp-t41-objs := tx_isp_t41_recovered.o \
		   tx_isp_t41_daynight.o \
		   tx_isp_t41_math.o \
		   tx_isp_t41_sinfo.o \
		   tx_isp_t41_subdev.o \
		   tx_isp_t41_frame_layout.o \
		   tx_isp_t41_exposure.o \
		   tx_isp_t41_awb_mesh.o \
		   tx_isp_t41_scaler.o \
		   tx_isp_t41_capture_gate.o \
		   tx_isp_t41_tuning_abi.o
ifneq ($(filter y m,$(CONFIG_VIDEOBUF2_DMA_CONTIG)),)
tx-isp-t41-$(CONFIG_TX_ISP_T41_V4L2) += \
					tx_isp_t41_video_queue.o \
					tx_isp_t41_v4l2.o
ccflags-$(CONFIG_TX_ISP_T41_V4L2) += -DCONFIG_TX_ISP_T41_V4L2
endif
obj-m += tx-isp-t41.o

ccflags-y += -I$(src)/../include
ccflags-y += -DREGTRACE_KERNEL_TREE_BUILD
ccflags-y += -std=gnu99
ccflags-y += -fpermissive
ccflags-y += -w
ccflags-y += -Wno-error=strict-prototypes
ccflags-y += -Wno-error=implicit-function-declaration
ccflags-y += -Wno-error=implicit-int
ccflags-y += -Wno-error=int-conversion
ccflags-y += -Wno-error=incompatible-pointer-types
