#!/usr/bin/env python3
"""Generate sensor-independent Q8 Gaussian kernels, no IQ bin or capture input.

These widths reproduce H20250310a kernelSStatic/kernelRStatic after Q8
quantization. Store only one octant / half of each symmetric kernel.
"""
import math


def coefficient(distance_squared, sigma):
    return min(255, int(256 * math.exp(-distance_squared / (2 * sigma * sigma))))


print('/* SPDX-License-Identifier: MIT */')
print('/* Generated by tools/gen_t41_tmo_kernels.py; not sensor tuning data. */')
print('#ifndef TX_ISP_T41_TMO_KERNELS_H\n#define TX_ISP_T41_TMO_KERNELS_H')
print('static const unsigned char t41_tmo_spatial_kernels[11][15] = {')
for width in (.5, .75, 1, 1.25, 1.5, 1.75, 2, 2.5, 3.5, 4.5, 6):
    values = [coefficient(x*x+y*y, width) for y in range(5) for x in range(y+1)]
    print('\t{ ' + ', '.join(map(str, values)) + ' }, /* sigma ' + str(width) + ' */')
print('};\nstatic const unsigned char t41_tmo_range_kernels[15][3] = {')
for width in (.5, .625, .75, .825, 1, 1.125, 1.25, 1.375, 1.5, 1.625, 1.75, 1.825, 2, 2.25, 2.5):
    print('\t{ ' + ', '.join(str(coefficient(x*x, width)) for x in range(3)) +
          ' }, /* sigma ' + str(width) + ' */')
print('};\n#endif')
