#!/usr/bin/env python3
"""Generate the exact T23 SC2336 GIB startup register image."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


TUNING_HEADER_SIZE = 0x18
GIB_CONFIG_OFFSET = 0x2A9C
GIB_RG_LINEAR_OFFSET = 0x2ACC
GIB_BIR_LINEAR_OFFSET = 0x2AD4
GIB_BLC_R_OFFSET = 0x2ADC
GIB_BLC_GR_OFFSET = 0x2B00
GIB_BLC_GB_OFFSET = 0x2B24
GIB_BLC_B_OFFSET = 0x2B48
GIB_BLC_IR_OFFSET = 0x2B6C
GIB_DEIR_R_M_OFFSET = 0x2D68
GIB_DEIR_G_M_OFFSET = 0x2DEC
GIB_DEIR_B_M_OFFSET = 0x2E70


def read_words(blob: bytes, parameter_offset: int, count: int) -> tuple[int, ...]:
    return struct.unpack_from(
        f"<{count}I", blob, TUNING_HEADER_SIZE + parameter_offset
    )


def gated(registers: list[tuple[int, int]], register: int, value: int) -> None:
    registers.append((0x1070, 1))
    registers.append((register, value))


def render(path: Path) -> str:
    blob = path.read_bytes()
    config = list(read_words(blob, GIB_CONFIG_OFFSET, 12))
    rg_linear = read_words(blob, GIB_RG_LINEAR_OFFSET, 2)
    bir_linear = read_words(blob, GIB_BIR_LINEAR_OFFSET, 2)
    blc = {
        "r": read_words(blob, GIB_BLC_R_OFFSET, 9)[0],
        "gr": read_words(blob, GIB_BLC_GR_OFFSET, 9)[0],
        "gb": read_words(blob, GIB_BLC_GB_OFFSET, 9)[0],
        "b": read_words(blob, GIB_BLC_B_OFFSET, 9)[0],
        "ir": read_words(blob, GIB_BLC_IR_OFFSET, 9)[0],
    }
    deir_r = read_words(blob, GIB_DEIR_R_M_OFFSET, 33)
    deir_g = read_words(blob, GIB_DEIR_G_M_OFFSET, 33)
    deir_b = read_words(blob, GIB_DEIR_B_M_OFFSET, 33)

    if any(value > 0xFFFF for value in (*rg_linear, *bir_linear, *blc.values())):
        raise ValueError("GIB startup coefficient exceeds its 16-bit register field")

    # OEM tiziano_gib_init clears DEIR enable after loading the tuning data.
    config[3] = 0
    reg1038 = (config[11] << 16) | config[10]
    reg103c = (
        (config[7] << 16)
        | (config[4] << 14)
        | (config[0] << 12)
        | (config[1] << 10)
        | (config[6] << 8)
        | (config[9] << 4)
        | (config[8] << 2)
    )
    reg106c = (config[3] << 16) | (config[2] << 3) | config[5]

    # Bayer pattern 1 maps B, Gb, Gr, R, IR to hardware channels 0..4.
    channels = (blc["b"], blc["gb"], blc["gr"], blc["r"], blc["ir"])
    registers: list[tuple[int, int]] = [(0x1038, reg1038), (0x103C, reg103c)]
    gated(registers, 0x106C, reg106c)
    gated(registers, 0x1060, channels[0])
    gated(registers, 0x1064, (channels[2] << 16) | channels[1])
    gated(registers, 0x1068, (channels[4] << 16) | channels[3])
    gated(registers, 0x1030, (rg_linear[1] << 16) | rg_linear[0])
    gated(registers, 0x1034, (bir_linear[1] << 16) | bir_linear[0])

    # tiziano_gib_init always streams the medium DEIR coefficient bank. The
    # SC2336 bank is zero, but retaining the writes matches the OEM sequence.
    for index in range(32):
        registers.append((0x80000 + index * 4, (deir_r[index + 1] << 12) | deir_r[index]))
        registers.append((0x80080 + index * 4, (deir_g[index + 1] << 12) | deir_g[index]))
        registers.append((0x80100 + index * 4, (deir_b[index + 1] << 12) | deir_b[index]))

    lines = [
        "/* Generated by tools/t23_gib_image.py. */",
        f"/* Source tuning SHA256: {hashlib.sha256(blob).hexdigest()} */",
        "/* SC2336 linear mode, Bayer pattern 1, startup analog gain 0. */",
        "static const uint32_t regtrace_t23_gib_sc2336_startup[][2] = {",
    ]
    lines.extend(
        f"    {{ 0x{register:05x}U, 0x{value:08x}U }},"
        for register, value in registers
    )
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
