#!/usr/bin/env python3
"""Generate the T23 YDNS tuning image from an OEM sensor tuning blob."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


HEADER_SIZE = 0x18
YDNS_OFFSET = 0x15570
CURVE_WORDS = 9


def render(path: Path) -> str:
    blob = path.read_bytes()
    names = (
        "mv_thres0",
        "mv_thres1",
        "mv_thres2",
        "fus_level",
        "fus_min_thres",
        "fus_max_thres",
        "fus_sswei",
        "fus_sewei",
        "fus_mswei",
        "fus_mewei",
        "fus_uvwei",
        "edge_wei",
        "edge_div",
        "edge_thres",
    )
    file_offset = HEADER_SIZE + YDNS_OFFSET
    edge_out = struct.unpack_from("<I", blob, file_offset)[0]
    curves = {}
    offset = file_offset + 4
    for name in names:
        curves[name] = struct.unpack_from(f"<{CURVE_WORDS}I", blob, offset)
        offset += CURVE_WORDS * 4

    digest = hashlib.sha256(blob).hexdigest()
    lines = [
        "/* Generated by tools/t23_ydns_image.py. */",
        f"/* Source tuning SHA256: {digest} */",
        f"#define REGTRACE_T23_YDNS_TUNING_FILE_OFFSET 0x{file_offset:x}U",
        "struct regtrace_t23_ydns_tuning_image {",
        "    uint32_t edge_out;",
    ]
    lines.extend(f"    uint32_t {name}[9];" for name in names)
    lines.extend([
        "};",
        "",
        "static const struct regtrace_t23_ydns_tuning_image",
        "regtrace_t23_ydns_sc2336 = {",
        f"    .edge_out = {edge_out}U,",
    ])
    for name in names:
        values = ", ".join(f"{value}U" for value in curves[name])
        lines.append(f"    .{name} = {{ {values} }},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
