#!/usr/bin/env python3
"""Generate the exact T23 SC2336 AWB statistics startup register image."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


TUNING_HEADER_SIZE = 0x18
AWB_PARAMETER_OFFSET = 0x1010
AWB_PARAMETER_WORDS = 45
AWB_ZONE_COLS = 15
AWB_ZONE_ROWS = 15
SENSOR_WIDTH = 1920
SENSOR_HEIGHT = 1080


def pack8(words: list[int]) -> int:
    return sum((word & 0xFF) << (index * 8) for index, word in enumerate(words))


def render(path: Path) -> str:
    blob = path.read_bytes()
    words = list(
        struct.unpack_from(
            f"<{AWB_PARAMETER_WORDS}I",
            blob,
            TUNING_HEADER_SIZE + AWB_PARAMETER_OFFSET,
        )
    )

    cell_width = (SENSOR_WIDTH // 2) // AWB_ZONE_COLS
    cell_height = (SENSOR_HEIGHT // 2) // AWB_ZONE_ROWS
    words[4:19] = [cell_width] * AWB_ZONE_COLS
    words[19:34] = [cell_height] * AWB_ZONE_ROWS

    if words[2] != 1:
        raise ValueError(f"unexpected T23 AWB input selector {words[2]}; expected 1")

    config = [
        (0xB004, (words[3] << 28) | (words[2] << 16) | (words[1] << 12) | words[0]),
        (0xB008, pack8(words[4:8])),
        (0xB00C, pack8(words[8:12])),
        (0xB010, pack8(words[12:16])),
        (0xB014, pack8(words[16:19])),
        (0xB018, pack8(words[19:23])),
        (0xB01C, pack8(words[23:27])),
        (0xB020, pack8(words[27:31])),
        (0xB024, pack8(words[31:34])),
    ]
    thresholds = [
        (0xB028, (words[35] << 16) | words[34]),
        (0xB02C, (words[37] << 16) | words[36]),
        (0xB030, (words[39] << 16) | words[38]),
        (0xB034, (words[41] << 16) | words[40]),
        (0xB038, (words[44] << 16) | (words[43] << 8) | words[42]),
    ]

    registers = list(config)
    for register, value in thresholds:
        registers.append((0xB000, 1))
        registers.append((register, value))

    lines = [
        "/* Generated by tools/t23_awb_stats_image.py. */",
        f"/* Source tuning SHA256: {hashlib.sha256(blob).hexdigest()} */",
        (
            f"/* {AWB_ZONE_COLS}x{AWB_ZONE_ROWS} zones; "
            f"half-resolution cells {cell_width}x{cell_height}. */"
        ),
        "/* T23 blob input selector preserved at b004 bit 16. */",
        "static const uint32_t regtrace_t23_awb_sc2336_stats_startup[][2] = {",
    ]
    lines.extend(
        f"    {{ 0x{register:05x}U, 0x{value:08x}U }},"
        for register, value in registers
    )
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
