#!/usr/bin/env python3
"""Generate the exact T23 CCM startup image from a tuning blob."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


TUNING_HEADER_SIZE = 0x18
CCM_DP_CFG_OFFSET = 0xB230
CCM_D_LINEAR_OFFSET = 0xB28C
CCM_EV_LIST_OFFSET = 0xB2D4
CCM_SAT_LIST_OFFSET = 0xB2F8
CCM_CT_LIST_OFFSET = 0xB3D0
AWB_EV_OFFSET = 0x1100
AWB_CT_OFFSET = 0x1104


def read_words(blob: bytes, parameter_offset: int, count: int) -> tuple[int, ...]:
    file_offset = TUNING_HEADER_SIZE + parameter_offset
    return struct.unpack_from(f"<{count}I", blob, file_offset)


def interpolate_saturation(
    ev: int, ev_list: tuple[int, ...], sat_list: tuple[int, ...]
) -> int:
    for index, ev_hi in enumerate(ev_list):
        if ev_hi < ev:
            continue
        if index == 0:
            return sat_list[0]

        ev_lo = ev_list[index - 1]
        sat_lo = sat_list[index - 1]
        sat_hi = sat_list[index]
        if ev_hi == ev_lo:
            return sat_hi
        distance = abs(ev - ev_lo)
        span = abs(ev_hi - ev_lo)
        if sat_hi >= sat_lo:
            return sat_lo + distance * (sat_hi - sat_lo) // span
        return sat_lo - distance * (sat_lo - sat_hi) // span
    return sat_list[-1]


def sign_extend_14(value: int) -> int:
    return value - 0x4000 if value >= 0x2000 else value


def fixed_mult_q16(left: int, right: int) -> int:
    """Equivalent to the OEM fix_point_mult2_32(16, left, right)."""
    return left * right >> 16


def apply_saturation(matrix: tuple[int, ...], saturation: int) -> tuple[int, ...]:
    r_luma = 0x4C8B
    g_luma = 0x9646
    b_luma = 0x1D2F
    saturation_matrix = (
        (saturation * 0xB375 >> 8) + r_luma,
        g_luma - (saturation * g_luma >> 8),
        b_luma - (saturation * b_luma >> 8),
        r_luma - (saturation * r_luma >> 8),
        (saturation * 0x69BA >> 8) + g_luma,
        b_luma - (saturation * b_luma >> 8),
        r_luma - (saturation * r_luma >> 8),
        g_luma - (saturation * g_luma >> 8),
        (saturation * 0xE2D1 >> 8) + b_luma,
    )
    signed_matrix = tuple(sign_extend_14(value) for value in matrix)
    result = []
    for row in range(3):
        for column in range(3):
            total = 0
            for index in range(3):
                coefficient = signed_matrix[row * 3 + index]
                sat_coefficient = saturation_matrix[index * 3 + column]
                product = fixed_mult_q16(
                    abs(coefficient) << 6, abs(sat_coefficient)
                )
                if (coefficient < 0) != (sat_coefficient < 0):
                    product = -product
                total += product
            result.append(total // 64 if total >= 0 else -((-total) // 64))
    return tuple(result)


def render(path: Path) -> str:
    blob = path.read_bytes()
    dp = read_words(blob, CCM_DP_CFG_OFFSET, 5)
    matrix_raw = read_words(blob, CCM_D_LINEAR_OFFSET, 9)
    ev_list = read_words(blob, CCM_EV_LIST_OFFSET, 9)
    sat_list = read_words(blob, CCM_SAT_LIST_OFFSET, 9)
    ct_list = read_words(blob, CCM_CT_LIST_OFFSET, 4)
    awb_ev = read_words(blob, AWB_EV_OFFSET, 1)[0]
    awb_ct = read_words(blob, AWB_CT_OFFSET, 1)[0]

    if any(value > 0x3FFF for value in matrix_raw):
        raise ValueError("CCM coefficient exceeds the T23 14-bit register format")
    if tuple(sorted(ev_list)) != ev_list:
        raise ValueError(f"CCM EV list is not sorted: {ev_list!r}")
    if tuple(sorted(ct_list)) != ct_list:
        raise ValueError(f"CCM CT list is not sorted: {ct_list!r}")
    if not (ct_list[2] - 200 <= awb_ct <= ct_list[2] + 200):
        raise ValueError(
            f"startup CT {awb_ct} does not select the daylight CCM plateau {ct_list[2]}"
        )

    ev = awb_ev >> 10
    saturation = interpolate_saturation(ev, ev_list, sat_list)
    matrix_signed = apply_saturation(matrix_raw, saturation)
    if any(value < -0x2000 or value >= 0x2000 for value in matrix_signed):
        raise ValueError(f"final CCM coefficient exceeds 14 bits: {matrix_signed!r}")
    matrix = tuple(value & 0x3FFF for value in matrix_signed)

    packed = [
        (matrix[1] << 16) | matrix[0],
        (matrix[3] << 16) | matrix[2],
        (matrix[5] << 16) | matrix[4],
        (matrix[7] << 16) | matrix[6],
        matrix[8],
    ]
    dp_step = 1 if dp[1] == dp[2] else 0x20 // abs(dp[2] - dp[1])
    dp_values = [
        (dp[1] << 16) | (dp[0] << 12) | dp[2],
        dp_step,
        (dp[4] << 16) | dp[3],
    ]

    lines = [
        "/* Generated by tools/t23_ccm_image.py. */",
        f"/* Source tuning SHA256: {hashlib.sha256(blob).hexdigest()} */",
        f"/* Startup CT {awb_ct}; CCM CT list: {', '.join(map(str, ct_list))}. */",
        f"/* Startup EV {awb_ev} >> 10 = {ev}; OEM saturation {saturation}/256. */",
        "static const uint32_t regtrace_t23_ccm_sc2336_daylight[][2] = {",
    ]
    for reg, value in zip(range(0x5004, 0x5018, 4), packed):
        lines.append(f"    {{ 0x{reg:04x}U, 0x{value:08x}U }},")
    for reg, value in zip(range(0x5018, 0x5024, 4), dp_values):
        lines.append(f"    {{ 0x{reg:04x}U, 0x{value:08x}U }},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
