#!/usr/bin/env python3
"""Generate the exact T23 SC2336 LSC startup register image."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


TUNING_HEADER_SIZE = 0x18
DEFAULT_STARTUP_CT = 5000
LSC_LUT_NUM_OFFSET = 0x3134
LSC_MESH_SCALE_OFFSET = 0x3138
LSC_LUT_STRIDE_OFFSET = 0x313C
LSC_MESH_SIZE_OFFSET = 0x3140
LSC_CT_POINTS_OFFSET = 0x3148
LSC_A_LUT_OFFSET = 0x3158
LSC_T_LUT_OFFSET = 0x5154
LSC_D_LUT_OFFSET = 0x7150
LSC_MESH_STRENGTH_OFFSET = 0x914C
LSC_MEAN_ENABLE_OFFSET = 0x9194


def read_words(blob: bytes, parameter_offset: int, count: int) -> tuple[int, ...]:
    return struct.unpack_from(
        f"<{count}I", blob, TUNING_HEADER_SIZE + parameter_offset
    )


def clamp12(value: int) -> int:
    return max(0, min(0xFFF, value))


def blend_word(lo_word: int, hi_word: int, weight: int) -> int:
    lo_low = lo_word & 0xFFF
    lo_high = lo_word >> 12
    hi_low = hi_word & 0xFFF
    hi_high = hi_word >> 12
    out_low = clamp12(lo_low + (((hi_low - lo_low) * weight) >> 12))
    out_high = clamp12(lo_high + (((hi_high - lo_high) * weight) >> 12))
    return (out_high << 12) | out_low


def scale_word(value: int, base: int, strength: int) -> int:
    low = clamp12(base + (((value & 0xFFF) - base) * strength >> 12))
    high = clamp12(base + (((value >> 12) - base) * strength >> 12))
    return (high << 12) | low


def render(path: Path, startup_ct: int, symbol: str) -> str:
    blob = path.read_bytes()
    lut_num = read_words(blob, LSC_LUT_NUM_OFFSET, 1)[0]
    mesh_scale = read_words(blob, LSC_MESH_SCALE_OFFSET, 1)[0]
    lut_stride = read_words(blob, LSC_LUT_STRIDE_OFFSET, 1)[0]
    mesh_size = read_words(blob, LSC_MESH_SIZE_OFFSET, 2)
    ct_points = read_words(blob, LSC_CT_POINTS_OFFSET, 4)
    mean_enable = read_words(blob, LSC_MEAN_ENABLE_OFFSET, 1)[0]
    strength = read_words(blob, LSC_MESH_STRENGTH_OFFSET, 9)[0]

    if lut_num == 0 or lut_num % 3:
        raise ValueError(f"LSC LUT word count must be a nonzero multiple of 3: {lut_num}")
    if tuple(sorted(ct_points)) != ct_points:
        raise ValueError(f"LSC CT points are not sorted: {ct_points!r}")
    a_lut = read_words(blob, LSC_A_LUT_OFFSET, lut_num)
    t_lut = read_words(blob, LSC_T_LUT_OFFSET, lut_num)
    d_lut = read_words(blob, LSC_D_LUT_OFFSET, lut_num)
    if startup_ct <= ct_points[0]:
        lo_lut, hi_lut, weight, zone = a_lut, a_lut, 0, "A"
    elif startup_ct <= ct_points[1]:
        lo_lut, hi_lut, zone = a_lut, t_lut, "A-to-T"
        weight = ((startup_ct - ct_points[0]) << 12) // (
            ct_points[1] - ct_points[0]
        )
    elif startup_ct <= ct_points[2]:
        lo_lut, hi_lut, weight, zone = t_lut, t_lut, 0, "T"
    elif startup_ct <= ct_points[3]:
        lo_lut, hi_lut, zone = t_lut, d_lut, "T-to-D"
        weight = ((startup_ct - ct_points[2]) << 12) // (
            ct_points[3] - ct_points[2]
        )
    else:
        lo_lut, hi_lut, weight, zone = d_lut, d_lut, 0, "D"
    blended = [
        blend_word(lo, hi, weight) for lo, hi in zip(lo_lut, hi_lut)
    ]

    if mesh_scale == 0:
        base = 0x800
    elif mesh_scale == 1:
        base = 0x400
    elif mesh_scale == 2:
        base = 0x200
    else:
        base = 0x100
    final_lut = [scale_word(value, base, strength) for value in blended]

    registers = [
        (0x3800, (mesh_size[1] << 16) | mesh_size[0]),
        (0x3804, (lut_stride << 16) | (mean_enable << 15) | mesh_scale),
    ]
    for index in range(0, lut_num, 3):
        register = 0x28000 + (index // 3) * 16
        registers.append((register, final_lut[index]))
        registers.append((register + 4, final_lut[index + 1]))
        registers.append((register + 8, final_lut[index + 2]))
    registers.append((0x2800C, 0))

    lines = [
        "/* Generated by tools/t23_lsc_image.py. */",
        f"/* Source tuning SHA256: {hashlib.sha256(blob).hexdigest()} */",
        (
            f"/* CT {startup_ct}; {zone} weight {weight}/4096; "
            f"strength {strength}/4096; {lut_num // 3} nodes. */"
        ),
        f"static const uint32_t {symbol}[][2] = {{",
    ]
    lines.extend(
        f"    {{ 0x{register:05x}U, 0x{value:08x}U }},"
        for register, value in registers
    )
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("--ct", type=lambda value: int(value, 0),
                        default=DEFAULT_STARTUP_CT)
    parser.add_argument("--symbol", default="regtrace_t23_lsc_sc2336_startup")
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob, args.ct, args.symbol)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
