#!/usr/bin/env python3
"""Generate the T23 SC2336 runtime AWB tables used by the active HLIL path."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


TUNING_HEADER_SIZE = 0x18

OFFSETS = {
    "pixel_count_threshold": (0x10C4, 1),
    "point_position": (0x10D0, 2),
    "history_control": (0x10D8, 2),
    "mf_parameters": (0x10E0, 6),
    "mode": (0x10F8, 3),
    "ev": (0x1100, 1),
    "ct": (0x1104, 1),
    "wb_static": (0x110C, 2),
    "rg_positions": (0x1168, 15),
    "bg_positions": (0x11A4, 15),
    "ct_parameters_outdoor": (0x1210, 2),
    "distance_parameters": (0x1220, 3),
    "color_temperature_mesh": (0x15B0, 225),
    "zone_weight_mesh": (0x1934, 225),
    "outdoor_inverse_ct_mesh": (0x1CB8, 225),
    "cluster_parameters": (0x284C, 10),
}


def read_words(blob: bytes, offset: int, count: int) -> tuple[int, ...]:
    return struct.unpack_from(f"<{count}I", blob, TUNING_HEADER_SIZE + offset)


def emit_array(name: str, values: tuple[int, ...]) -> list[str]:
    lines = [f"static const uint32_t {name}[{len(values)}] = {{"]
    for index in range(0, len(values), 8):
        row = ", ".join(f"0x{value:08x}U" for value in values[index : index + 8])
        lines.append(f"    {row},")
    lines.append("};")
    return lines


def render(path: Path) -> str:
    blob = path.read_bytes()
    values = {
        name: read_words(blob, offset, count)
        for name, (offset, count) in OFFSETS.items()
    }

    point_position = values["point_position"]
    mode = values["mode"]
    ev = values["ev"][0]
    cluster = values["cluster_parameters"]
    ct_parameters = values["ct_parameters_outdoor"]

    if point_position[0] != 10:
        raise ValueError(f"unexpected AWB fixed-point position: {point_position!r}")
    if tuple(sorted(values["rg_positions"])) != values["rg_positions"]:
        raise ValueError("AWB rg position table is not sorted")
    if tuple(sorted(values["bg_positions"])) != values["bg_positions"]:
        raise ValueError("AWB bg position table is not sorted")
    if ev >= mode[0] << 10:
        raise ValueError(
            f"startup EV {ev} does not select the outdoor AWB path {mode[0] << 10}"
        )
    if cluster[0] != 0:
        raise ValueError(f"SC2336 AWB cluster mode is unexpectedly enabled: {cluster!r}")
    if ct_parameters[0] != 0:
        raise ValueError(
            "SC2336 outdoor AWB CT edge weighting is unexpectedly enabled"
        )
    if values["distance_parameters"][0] != 1:
        raise ValueError("SC2336 AWB distance refinement is unexpectedly disabled")

    lines = [
        "/* Generated by tools/t23_awb_runtime_image.py. */",
        f"/* Source tuning SHA256: {hashlib.sha256(blob).hexdigest()} */",
        "/* Active startup path: outdoor mesh, no CT edge weighting, no clusters. */",
        f"#define REGTRACE_T23_AWB_HLIL_PIXEL_THRESHOLD {values['pixel_count_threshold'][0]}U",
        f"#define REGTRACE_T23_AWB_HLIL_POINT_POSITION {point_position[0]}U",
        f"#define REGTRACE_T23_AWB_HLIL_HISTORY_WINDOW {values['history_control'][0]}U",
        f"#define REGTRACE_T23_AWB_HLIL_STARTUP_EV {ev}U",
        f"#define REGTRACE_T23_AWB_HLIL_STARTUP_CT {values['ct'][0]}U",
        "",
    ]

    emitted = (
        ("regtrace_t23_awb_hlil_mf_parameters", "mf_parameters"),
        ("regtrace_t23_awb_hlil_wb_static", "wb_static"),
        ("regtrace_t23_awb_hlil_rg_positions", "rg_positions"),
        ("regtrace_t23_awb_hlil_bg_positions", "bg_positions"),
        ("regtrace_t23_awb_hlil_distance_parameters", "distance_parameters"),
        ("regtrace_t23_awb_hlil_color_temperature_mesh", "color_temperature_mesh"),
        ("regtrace_t23_awb_hlil_zone_weight_mesh", "zone_weight_mesh"),
        ("regtrace_t23_awb_hlil_outdoor_inverse_ct_mesh", "outdoor_inverse_ct_mesh"),
    )
    for c_name, value_name in emitted:
        lines.extend(emit_array(c_name, values[value_name]))
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
