#!/usr/bin/env python3
"""Generate the T23 sharpen startup register image from an OEM tuning blob."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


HEADER_SIZE = 0x18
SHARPEN_OFFSET = 0xB3E0


def words(blob: bytes, offset: int, count: int) -> tuple[int, ...]:
    return struct.unpack_from(f"<{count}I", blob, HEADER_SIZE + offset)


def curve(blob: bytes, offset: int, gain_q16: int) -> int:
    values = words(blob, offset, 9)
    index = gain_q16 >> 16
    fraction = gain_q16 & 0xFFFF
    if index >= 8:
        return values[8]
    low = values[index]
    high = values[index + 1]
    delta = abs(high - low) * fraction
    delta = (delta >> 16) + ((delta & 0x8000) >> 15)
    return low + delta if high >= low else low - delta


def render(path: Path, gain_q16: int, symbol: str) -> str:
    blob = path.read_bytes()
    c = lambda offset: curve(blob, SHARPEN_OFFSET + offset, gain_q16)
    w = lambda offset, count: words(blob, SHARPEN_OFFSET + offset, count)
    out_opt = w(0x000, 1)[0]
    std = w(0x04C, 2)
    uu_cfg = w(0x12C, 4)
    fl_cfg = w(0x214, 2)
    coef = w(0x240, 12)
    wb_ll = w(0x270, 9)
    uu_np = w(0x294, 16)
    w_np = w(0x2D4, 16)
    b_np = w(0x314, 16)

    sl_exp_thres = c(0x004)
    sl_exp_num = c(0x028)
    uu_min_stren = c(0x054)
    uu_min_thres = c(0x078)
    uu_thres = c(0x09C)
    mv_uu_thres = c(0x0C0)
    mv_uu_stren = c(0x0E4)
    uu_stren = c(0x108)
    fl_std_thres = c(0x13C)
    mv_fl_std_thres = c(0x160)
    fl_thres = c(0x184)
    fl_min_thres = c(0x1A8)
    mv_fl_thres = c(0x1CC)
    mv_fl_min_thres = c(0x1F0)
    v2_win5_thres = c(0x21C)
    w_sl = [c(0x354 + index * 0x24) for index in range(4)]
    b_sl = [c(0x3E4 + index * 0x24) for index in range(4)]
    uu_sl = [c(0x474 + index * 0x24) for index in range(4)]
    fl_sl = [c(offset) for offset in (0x504, 0x528, 0x54C, 0x6B4)]

    writes = [
        (0x7000, (sl_exp_num << 16) | sl_exp_thres),
        (0x7004, (std[0] << 16) | std[1]),
        (0x7008, (uu_min_stren << 16) | uu_cfg[0] | (uu_cfg[1] << 8)),
        (0x700C, (mv_uu_thres << 24) | (uu_thres << 8) |
                 uu_min_thres | (uu_cfg[2] << 16)),
        (0x7010, (out_opt << 28) | (uu_cfg[3] << 24) |
                 (uu_stren << 8) | mv_uu_stren),
        (0x7014, (mv_fl_std_thres << 8) | fl_std_thres),
        (0x7018, (fl_thres << 16) | fl_cfg[0] | (fl_min_thres << 24)),
        (0x701C, (mv_fl_thres << 16) | fl_cfg[1] |
                 (mv_fl_min_thres << 24)),
        (0x7020, (v2_win5_thres << 8) | coef[0] | (coef[1] << 16)),
        (0x7024, coef[2] | (coef[3] << 4) | (coef[4] << 8) |
                 (coef[5] << 12) | (coef[6] << 16) | (coef[7] << 20)),
        (0x7028, coef[8] | (coef[9] << 8) | (coef[10] << 16) |
                 (coef[11] << 24)),
        (0x702C, wb_ll[0] | (wb_ll[1] << 8) | (wb_ll[2] << 16) |
                 (wb_ll[3] << 24)),
        (0x7030, wb_ll[4] | (wb_ll[5] << 8) | (wb_ll[6] << 16)),
        (0x7034, wb_ll[7] | (wb_ll[8] << 16)),
    ]
    for base, values in ((0x7038, uu_np), (0x7048, w_np), (0x7058, b_np)):
        for index in range(0, 16, 4):
            value = (values[index] | (values[index + 1] << 8) |
                     (values[index + 2] << 16) | (values[index + 3] << 24))
            writes.append((base + index, value))
    writes.extend([
        (0x7068, w_sl[0] | (w_sl[1] << 16)),
        (0x706C, w_sl[2] | (w_sl[3] << 16)),
        (0x7070, b_sl[0] | (b_sl[1] << 16)),
        (0x7074, b_sl[2] | (b_sl[3] << 16)),
        (0x7078, uu_sl[0] | (uu_sl[1] << 8) | (uu_sl[2] << 16) |
                 (uu_sl[3] << 24)),
        (0x707C, fl_sl[0] | (fl_sl[1] << 8) | (fl_sl[2] << 16) |
                 (fl_sl[3] << 24)),
        (0x7090, 1),
    ])

    digest = hashlib.sha256(blob).hexdigest()
    lines = [
        "/* Generated by tools/t23_sharpen_image.py. */",
        f"/* Source tuning SHA256: {digest} */",
        f"/* Total gain: 0x{gain_q16:08x} Q16. */",
        f"static const uint32_t {symbol}[][2] = {{",
    ]
    lines.extend(
        f"    {{ 0x{register:04x}U, 0x{value & 0xFFFFFFFF:08x}U }},"
        for register, value in writes
    )
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("--gain-q16", type=lambda value: int(value, 0), default=0x10000)
    parser.add_argument("--symbol", default="regtrace_t23_sharpen_sc2336_startup")
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob, args.gain_q16, args.symbol)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
