#!/usr/bin/env python3
"""Generate the exact T23 daylight CCM startup image from a tuning blob."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


TUNING_HEADER_SIZE = 0x18
CCM_DP_CFG_OFFSET = 0xB230
CCM_D_LINEAR_OFFSET = 0xB28C
CCM_CT_LIST_OFFSET = 0xB3D0
AWB_CT_OFFSET = 0x1104


def read_words(blob: bytes, parameter_offset: int, count: int) -> tuple[int, ...]:
    file_offset = TUNING_HEADER_SIZE + parameter_offset
    return struct.unpack_from(f"<{count}I", blob, file_offset)


def render(path: Path) -> str:
    blob = path.read_bytes()
    dp = read_words(blob, CCM_DP_CFG_OFFSET, 5)
    matrix = read_words(blob, CCM_D_LINEAR_OFFSET, 9)
    ct_list = read_words(blob, CCM_CT_LIST_OFFSET, 4)
    awb_ct = read_words(blob, AWB_CT_OFFSET, 1)[0]

    if any(value > 0x3FFF for value in matrix):
        raise ValueError("CCM coefficient exceeds the T23 14-bit register format")
    if tuple(sorted(ct_list)) != ct_list:
        raise ValueError(f"CCM CT list is not sorted: {ct_list!r}")
    if not (ct_list[2] - 200 <= awb_ct <= ct_list[2] + 200):
        raise ValueError(
            f"startup CT {awb_ct} does not select the daylight CCM plateau {ct_list[2]}"
        )

    packed = [
        (matrix[1] << 16) | matrix[0],
        (matrix[3] << 16) | matrix[2],
        (matrix[5] << 16) | matrix[4],
        (matrix[7] << 16) | matrix[6],
        matrix[8],
    ]
    dp_step = 1 if dp[1] == dp[2] else 0x20 // abs(dp[2] - dp[1])
    dp_values = [
        (dp[1] << 16) | (dp[0] << 12) | dp[2],
        dp_step,
        (dp[4] << 16) | dp[3],
    ]

    lines = [
        "/* Generated by tools/t23_ccm_image.py. */",
        f"/* Source tuning SHA256: {hashlib.sha256(blob).hexdigest()} */",
        f"/* Startup CT {awb_ct}; CCM CT list: {', '.join(map(str, ct_list))}. */",
        "static const uint32_t regtrace_t23_ccm_sc2336_daylight[][2] = {",
    ]
    for reg, value in zip(range(0x5004, 0x5018, 4), packed):
        lines.append(f"    {{ 0x{reg:04x}U, 0x{value:08x}U }},")
    for reg, value in zip(range(0x5018, 0x5024, 4), dp_values):
        lines.append(f"    {{ 0x{reg:04x}U, 0x{value:08x}U }},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
