#!/usr/bin/env python3
"""Generate the exact T23 SC2336 AE0 statistics startup register image."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


TUNING_HEADER_SIZE = 0x18
AE_PARAMETER_OFFSET = 0x80
AE_PARAMETER_WORDS = 42


def read_words(blob: bytes, parameter_offset: int, count: int) -> tuple[int, ...]:
    return struct.unpack_from(
        f"<{count}I", blob, TUNING_HEADER_SIZE + parameter_offset
    )


def pack4(values: tuple[int, ...], indices: tuple[int, int, int, int]) -> int:
    return (
        values[indices[0]]
        | (values[indices[1]] << 8)
        | (values[indices[2]] << 16)
        | (values[indices[3]] << 24)
    )


def render(path: Path) -> str:
    blob = path.read_bytes()
    words = read_words(blob, AE_PARAMETER_OFFSET, AE_PARAMETER_WORDS)

    reg_a004 = (
        words[0] | (words[1] << 12) | (words[2] << 16) | (words[3] << 28)
    )
    reg_a014 = words[16] | (words[17] << 8) | (words[18] << 16)
    reg_a024 = words[31] | (words[32] << 8) | (words[33] << 16)
    reg_a028 = words[34] | (words[36] << 16) | (words[37] << 20)
    if words[35] < 0xFF:
        reg_a028 |= ((words[35] * 2) // 3) << 8
    else:
        reg_a028 |= words[35] << 8

    registers = (
        (0xA004, reg_a004),
        (0xA008, pack4(words, (4, 5, 6, 7))),
        (0xA00C, pack4(words, (8, 9, 10, 11))),
        (0xA010, pack4(words, (12, 13, 14, 15))),
        (0xA014, reg_a014),
        (0xA018, pack4(words, (19, 20, 21, 22))),
        (0xA01C, pack4(words, (23, 24, 25, 26))),
        (0xA020, pack4(words, (27, 28, 29, 30))),
        (0xA024, reg_a024),
        (0xA028, reg_a028),
    )

    if any(value > 0xFFFFFFFF for _, value in registers):
        raise ValueError("AE0 startup value exceeds its 32-bit register")

    lines = [
        "/* Generated by tools/t23_ae_stats_image.py. */",
        f"/* Source tuning SHA256: {hashlib.sha256(blob).hexdigest()} */",
        "static const uint32_t regtrace_t23_ae0_sc2336_stats_startup[][2] = {",
    ]
    lines.extend(
        f"    {{ 0x{register:04x}U, 0x{value:08x}U }},"
        for register, value in registers
    )
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
