#!/usr/bin/env python3
"""Generate the T23 linear Gamma LUT include from an OEM tuning blob."""

import argparse
import hashlib
from pathlib import Path


GAMMA_FILE_OFFSET = 0x28B0
GAMMA_LUT_SIZE = 0x102
GAMMA_POINT_COUNT = 129


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_bin", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    return parser.parse_args()


def render(image):
    end = GAMMA_FILE_OFFSET + GAMMA_LUT_SIZE
    if len(image) < end:
        raise ValueError(
            f"tuning blob is too short: 0x{len(image):x}, need at least 0x{end:x}"
        )
    data = image[GAMMA_FILE_OFFSET:end]
    points = [
        int.from_bytes(data[offset : offset + 2], "little")
        for offset in range(0, len(data), 2)
    ]
    if len(points) != GAMMA_POINT_COUNT or any(point > 0xFFF for point in points):
        raise ValueError("unexpected T23 Gamma LUT shape or point range")

    digest = hashlib.sha256(image).hexdigest()
    lines = [
        "/* Generated by tools/t23_gamma_image.py. */",
        f"/* Source tuning SHA256: {digest} */",
        "static const uint32_t regtrace_t23_gamma_sc2336_linear[] = {",
    ]
    for index in range(GAMMA_POINT_COUNT - 1):
        packed = points[index] | (points[index + 1] << 12)
        lines.append(
            f"    0x{packed:08x}U, /* {index:3d}: {points[index]:4d}, "
            f"{points[index + 1]:4d} */"
        )
    lines.extend(["};", ""])
    return "\n".join(lines)


def main():
    args = parse_args()
    output = render(args.tuning_bin.read_bytes())
    if args.output:
        args.output.write_text(output)
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
