#!/usr/bin/env python3
"""Recover the T23 ADR tuning layout from retained OEM relocations."""

import argparse
import json
import re
import subprocess
from pathlib import Path


PARAMS_KEY = "fn_0000000000033dac|tiziano_adr_params_refresh|33dac|574"
TPARAMS_FILE_BIAS = 0x130E8


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("mcp_cache", type=Path)
    parser.add_argument("original_ko", type=Path)
    parser.add_argument("--objdump", default="objdump")
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def cache_text(cache):
    data = json.loads(cache.read_text())
    return data["functions"][PARAMS_KEY]["decompiled_text"]


def parse_destinations(text):
    pattern = re.compile(
        r"^memcpy\(&([A-Za-z0-9_]+), .*?, (0x[0-9a-fA-F]+|[0-9]+)\)$",
        re.MULTILINE,
    )
    fields = [(name, int(size, 0)) for name, size in pattern.findall(text)]
    # The final memcpy is the runtime selection into the centre-weight array,
    # not another source-tuning reference.
    if len(fields) != 39:
        raise ValueError(f"unexpected ADR memcpy count: {len(fields)}")
    fields = fields[:38]
    if fields[-1][0] != "var_40" or fields[-1][1] != 0x38:
        raise ValueError(f"unexpected ADR tool-control field: {fields[-1]}")
    fields[-1] = ("param_adr_tool_control_array", fields[-1][1])
    fields.extend(
        [
            ("param_adr_weight_20_lut_array", 0x80),
            ("param_adr_weight_02_lut_array", 0x80),
            ("param_adr_weight_12_lut_array", 0x80),
            ("param_adr_weight_22_lut_array", 0x80),
            ("param_adr_weight_21_lut_array", 0x80),
            ("param_adr_centre_w_dis_array", 0x7C),
        ]
    )
    return fields


def function_disassembly(objdump, module, name):
    output = subprocess.check_output([objdump, "-dr", str(module)], text=True)
    match = re.search(
        rf"^[0-9a-f]+ <{re.escape(name)}>:\n(.*?)(?=^[0-9a-f]+ <|\Z)",
        output,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        raise ValueError(f"function not found in objdump output: {name}")
    return match.group(1)


def parse_tparams_offsets(disassembly):
    hi_pattern = re.compile(
        r"^[^\n]*\blui\s+a1,0x([0-9a-fA-F]+)\n"
        r"\s*[^\n]*R_MIPS_HI16\s+tparams\s*$",
        re.MULTILINE,
    )
    lo_pattern = re.compile(
        r"^[^\n]*\baddiu\s+a1,a1,(-?[0-9]+)\n"
        r"\s*[^\n]*R_MIPS_LO16\s+tparams\s*$",
        re.MULTILINE,
    )
    highs = [int(value, 16) for value in hi_pattern.findall(disassembly)]
    lows = [int(value, 10) for value in lo_pattern.findall(disassembly)]
    if len(highs) != 44 or len(lows) != 44:
        raise ValueError(
            f"unexpected ADR tparams relocation count: hi={len(highs)} lo={len(lows)}"
        )
    return [(hi << 16) + lo - TPARAMS_FILE_BIAS for hi, lo in zip(highs, lows)]


def render_layout(fields, offsets):
    start = min(offsets)
    end = max(offset + size for (_, size), offset in zip(fields, offsets))
    occupied = []

    for (name, size), offset in zip(fields, offsets):
        if offset < 0:
            raise ValueError(f"negative ADR file offset for {name}: {offset}")
        for prior_name, prior_start, prior_end in occupied:
            if offset < prior_end and offset + size > prior_start:
                raise ValueError(
                    f"overlapping ADR fields: {name} and {prior_name}"
                )
        occupied.append((name, offset, offset + size))

    lines = [
        "/* Generated by tools/t23_adr_layout.py. */",
        f"#define REGTRACE_T23_ADR_TUNING_OFFSET 0x{start:x}U",
        f"#define REGTRACE_T23_ADR_TUNING_SIZE 0x{end - start:x}U",
        "#define REGTRACE_T23_ADR_TUNING_FIELDS(X) \\",
    ]
    for index, ((name, size), offset) in enumerate(zip(fields, offsets)):
        suffix = " \\" if index + 1 != len(fields) else ""
        lines.append(
            f"    X({name}, 0x{offset - start:04x}U, 0x{size:x}U){suffix}"
        )
    return "\n".join(lines) + "\n"


def main():
    args = parse_args()
    fields = parse_destinations(cache_text(args.mcp_cache))
    disassembly = function_disassembly(
        args.objdump, args.original_ko, "tiziano_adr_params_refresh"
    )
    offsets = parse_tparams_offsets(disassembly)
    args.output.write_text(render_layout(fields, offsets))


if __name__ == "__main__":
    main()
