#!/usr/bin/env python3
"""Recover the T23 SDNS tuning layout and source register writers.

The OEM module retains relocations for each tparams access.  Pairing those
offsets with the decompiler's memcpy destinations recovers the exact T23
layout.  The register writers come from the checked-in T31 source recovery;
SDNS register packing is shared, while the T23 Gaussian-Y constant is kept.
"""

import argparse
import json
import re
import subprocess
from pathlib import Path


PARAMS_KEY = "fn_0000000000040750|tiziano_sdns_params_refresh|40750|bd0"
TPARAMS_FILE_BIAS = 0x130E8
SDNS_FILE_OFFSET = 0xBF18
SDNS_FILE_END = 0xD1D0
WRITER_NAMES = [
    "tisp_sdns_grad_thres_opt_cfg",
    "tisp_sdns_h_mv_wei_opt_cfg",
    "tisp_sdns_mv_seg_number_num_thres_cfg",
    "tisp_sdns_g_det_val_div_cfg",
    "tisp_sdns_r_s_mv_cfg",
    "tisp_sdns_h_s_cfg",
    "tisp_sdns_h_mv_cfg",
    "tisp_sdns_dark_light_tt_opt_cfg",
    "tisp_sdns_d_s1_thres_cfg",
    "tisp_sdns_w_thres_cfg",
    "tisp_sdns_hls_en_ave_filter_cfg",
    "tisp_sdns_gaussian_y_cfg",
    "tisp_sdns_gaussian_x_cfg",
    "tisp_sdns_gaussian_k_cfg",
    "tisp_sdns_h_line_cfg",
    "tisp_sdns_sp_std_en_seg_opt_cfg",
    "tisp_sdns_sp_uu_cfg",
    "tisp_sdns_sp_v2_d_w_b_ll_hl_flat_cfg",
    "tisp_sdns_sp_ud_v2_v1_coef_w_wei_opt_cfg",
    "tisp_sdns_sp_ud_w_stren_cfg",
    "tisp_sdns_sp_ud_w_limit_b_wei_opt_cfg",
    "tisp_sdns_sp_ud_b_stren_cfg",
    "tisp_sdns_sp_ud_b_limit_srd_ll_hl_flat_cfg",
    "tisp_sdns_sp_ud_stren_shift_opt_cfg",
    "tisp_sdns_sp_uu_np_array_cfg",
    "tisp_sdns_sp_d_w_wei_np_array_cfg",
    "tisp_sdns_sp_d_b_wei_np_array_cfg",
    "tisp_sdns_sp_ud_w_wei_np_array_cfg",
    "tisp_sdns_sp_ud_b_wei_np_array_cfg",
]


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("mcp_cache", type=Path)
    parser.add_argument("original_ko", type=Path)
    parser.add_argument("--objdump", default="objdump")
    parser.add_argument("--layout-output", type=Path, required=True)
    parser.add_argument("--t31-source", type=Path, required=True)
    parser.add_argument("--writers-output", type=Path, required=True)
    return parser.parse_args()


def cache_text(cache, key):
    data = json.loads(cache.read_text())
    return data["functions"][key]["decompiled_text"]


def parse_destinations(text):
    pattern = re.compile(
        r"^memcpy\(&([A-Za-z0-9_]+), .*?, (0x[0-9a-fA-F]+|[0-9]+)\)$",
        re.MULTILINE,
    )
    fields = [(name, int(size, 0)) for name, size in pattern.findall(text)]
    if len(fields) != 123:
        raise ValueError(f"unexpected SDNS memcpy count: {len(fields)}")
    return fields


def function_disassembly(objdump, module, name):
    output = subprocess.check_output([objdump, "-dr", str(module)], text=True)
    match = re.search(
        rf"^[0-9a-f]+ <{re.escape(name)}>:\n(.*?)(?=^[0-9a-f]+ <|\Z)",
        output,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        raise ValueError(f"function not found in objdump output: {name}")
    return match.group(1)


def parse_tparams_offsets(disassembly):
    hi_pattern = re.compile(
        r"^[^\n]*\blui\s+a1,0x([0-9a-fA-F]+)\n"
        r"\s*[^\n]*R_MIPS_HI16\s+tparams\s*$",
        re.MULTILINE,
    )
    lo_pattern = re.compile(
        r"^[^\n]*\baddiu\s+a1,a1,(-?[0-9]+)\n"
        r"\s*[^\n]*R_MIPS_LO16\s+tparams\s*$",
        re.MULTILINE,
    )
    highs = [int(value, 16) for value in hi_pattern.findall(disassembly)]
    lows = [int(value, 10) for value in lo_pattern.findall(disassembly)]
    if len(highs) != 123 or len(lows) != 123:
        raise ValueError(
            f"unexpected tparams relocation count: hi={len(highs)} lo={len(lows)}"
        )
    return [(hi << 16) + lo - TPARAMS_FILE_BIAS for hi, lo in zip(highs, lows)]


def render_layout(fields, offsets):
    lines = [
        "/* Generated by tools/t23_sdns_layout.py. */",
        f"#define REGTRACE_T23_SDNS_TUNING_OFFSET 0x{SDNS_FILE_OFFSET:x}U",
        f"#define REGTRACE_T23_SDNS_TUNING_SIZE 0x{SDNS_FILE_END - SDNS_FILE_OFFSET:x}U",
        "#define REGTRACE_T23_SDNS_TUNING_FIELDS(X) \\",
    ]
    expected = SDNS_FILE_OFFSET
    for index, ((name, size), offset) in enumerate(zip(fields, offsets)):
        if offset != expected:
            raise ValueError(
                f"non-contiguous SDNS field: {name} offset=0x{offset:x} expected=0x{expected:x}"
            )
        if offset + size > SDNS_FILE_END:
            raise ValueError(
                f"SDNS field outside payload: {name} offset=0x{offset:x} size=0x{size:x}"
            )
        expected = offset + size
        suffix = " \\" if index + 1 != len(fields) else ""
        lines.append(
            f"    X({name}, 0x{offset - SDNS_FILE_OFFSET:04x}U, 0x{size:x}U){suffix}"
        )
    if expected != SDNS_FILE_END:
        raise ValueError(f"SDNS payload ended at 0x{expected:x}, expected 0x{SDNS_FILE_END:x}")
    return "\n".join(lines) + "\n"


def extract_c_function(source, name):
    match = re.search(
        rf"^static void {re.escape(name)}\(void\)\s*\{{",
        source,
        re.MULTILINE,
    )
    if not match:
        raise ValueError(f"function not found in T31 source: {name}")
    brace = source.index("{", match.start())
    depth = 0
    for index in range(brace, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[match.start() : index + 1]
    raise ValueError(f"unterminated function in T31 source: {name}")


def render_writers(source):
    functions = []
    array_access = re.compile(r"\b(sdns_[A-Za-z0-9_]+)\[([^\[\]]+)\]")
    for name in WRITER_NAMES:
        function = extract_c_function(source, name)
        function = re.sub(
            rf"\b{re.escape(name)}\b", f"regtrace_t23_{name[5:]}", function
        )
        function = function.replace("static void", "static noinline void", 1)
        function = array_access.sub(
            lambda match: (
                f"REGTRACE_T23_SDNS_WORD({match.group(1)}, {match.group(2)})"
            ),
            function,
        )
        if name == "tisp_sdns_gaussian_y_cfg":
            function = function.replace("0x3999a", "0x2999a")
        functions.append(function)

    return (
        "/* Generated from the checked-in T31 SDNS source reference. */\n"
        "#define REGTRACE_T23_SDNS_WORD(base, index) \\\n"
        "    (*(const uint32_t *)((uintptr_t)(base) + (uintptr_t)(index) * 4U))\n\n"
        + "\n\n".join(functions)
        + "\n\n#undef REGTRACE_T23_SDNS_WORD\n"
    )


def main():
    args = parse_args()
    params = cache_text(args.mcp_cache, PARAMS_KEY)
    fields = parse_destinations(params)
    disassembly = function_disassembly(
        args.objdump, args.original_ko, "tiziano_sdns_params_refresh"
    )
    offsets = parse_tparams_offsets(disassembly)

    args.layout_output.write_text(render_layout(fields, offsets))
    args.writers_output.write_text(render_writers(args.t31_source.read_text()))


if __name__ == "__main__":
    main()
