#!/usr/bin/env python3
"""Recover the T23 MDNS tuning layout and interpolation assignments.

The OEM module retains relocations for every tparams access.  Combining those
with the decompiler's destination names recovers the exact, non-contiguous
MDNS field layout without depending on Binary Ninja's displayed data labels.
"""

import argparse
import json
import re
import subprocess
from pathlib import Path


PARAMS_KEY = "fn_00000000000617d4|tiziano_mdns_params_refresh|617d4|2ca0"
INTP_KEY = "fn_00000000000584a8|tisp_mdns_intp|584a8|298c"
TPARAMS_FILE_BIAS = 0x130E8
MDNS_FILE_OFFSET = 0xD1D0
MDNS_FILE_END = 0x1122C


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("mcp_cache", type=Path)
    parser.add_argument("original_ko", type=Path)
    parser.add_argument("--objdump", default="objdump")
    parser.add_argument("--layout-output", type=Path, required=True)
    parser.add_argument("--interpolation-output", type=Path, required=True)
    parser.add_argument("--t31-source", type=Path)
    parser.add_argument("--writers-output", type=Path)
    return parser.parse_args()


def cache_text(cache, key):
    data = json.loads(cache.read_text())
    return data["functions"][key]["decompiled_text"]


def parse_destinations(text):
    pattern = re.compile(
        r"^memcpy\(&([A-Za-z0-9_]+), .*?, (0x[0-9a-fA-F]+|[0-9]+)\)$",
        re.MULTILINE,
    )
    fields = [(name, int(size, 0)) for name, size in pattern.findall(text)]
    if len(fields) != 473:
        raise ValueError(f"unexpected MDNS memcpy count: {len(fields)}")
    return fields


def function_disassembly(objdump, module, name):
    output = subprocess.check_output([objdump, "-dr", str(module)], text=True)
    match = re.search(
        rf"^[0-9a-f]+ <{re.escape(name)}>:\n(.*?)(?=^[0-9a-f]+ <|\Z)",
        output,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        raise ValueError(f"function not found in objdump output: {name}")
    return match.group(1)


def parse_tparams_offsets(disassembly):
    hi_pattern = re.compile(
        r"^[^\n]*\blui\s+a1,0x([0-9a-fA-F]+)\n"
        r"\s*[^\n]*R_MIPS_HI16\s+tparams\s*$",
        re.MULTILINE,
    )
    lo_pattern = re.compile(
        r"^[^\n]*\baddiu\s+a1,a1,(-?[0-9]+)\n"
        r"\s*[^\n]*R_MIPS_LO16\s+tparams\s*$",
        re.MULTILINE,
    )
    highs = [int(value, 16) for value in hi_pattern.findall(disassembly)]
    lows = [int(value, 10) for value in lo_pattern.findall(disassembly)]
    if len(highs) != 473 or len(lows) != 473:
        raise ValueError(
            f"unexpected tparams relocation count: hi={len(highs)} lo={len(lows)}"
        )
    return [(hi << 16) + lo - TPARAMS_FILE_BIAS for hi, lo in zip(highs, lows)]


def parse_interpolation(text):
    pattern = re.compile(
        r"^(mdns_[A-Za-z0-9_]+_intp)\s*=\s*tisp_simple_intp\("
        r"[^,]+,\s*[^,]+,\s*(&?)(mdns_[A-Za-z0-9_]+(?:_array|_array_now))\)$",
        re.MULTILINE,
    )
    fields = [
        (destination, source, 0 if address_of else 1)
        for destination, address_of, source in pattern.findall(text)
    ]
    if len(fields) != 377 or len(set(fields)) != len(fields):
        raise ValueError(f"unexpected MDNS interpolation count: {len(fields)}")
    return fields


def render_layout(fields, offsets):
    lines = [
        "/* Generated by tools/t23_mdns_layout.py. */",
        "#define REGTRACE_T23_MDNS_TUNING_FIELDS(X) \\",
    ]
    for index, ((name, size), offset) in enumerate(zip(fields, offsets)):
        if not MDNS_FILE_OFFSET <= offset <= MDNS_FILE_END - size:
            raise ValueError(
                f"MDNS field outside payload: {name} offset=0x{offset:x} size=0x{size:x}"
            )
        suffix = " \\" if index + 1 != len(fields) else ""
        lines.append(
            f"    X({name}, 0x{offset - MDNS_FILE_OFFSET:04x}U, 0x{size:x}U){suffix}"
        )
    return "\n".join(lines) + "\n"


def render_interpolation(fields):
    lines = [
        "/* Generated by tools/t23_mdns_layout.py. */",
        "#define REGTRACE_T23_MDNS_INTERPOLATED_FIELDS(X) \\",
    ]
    for index, (destination, source, indirect) in enumerate(fields):
        suffix = " \\" if index + 1 != len(fields) else ""
        lines.append(f"    X({destination}, {source}, {indirect}){suffix}")
    return "\n".join(lines) + "\n"


def extract_c_function(source, name):
    match = re.search(
        rf"^static(?: inline)? [^\n]+\b{re.escape(name)}\([^\n]*\)\n\{{",
        source,
        re.MULTILINE,
    )
    if not match:
        raise ValueError(f"function not found in T31 source: {name}")
    brace = source.index("{", match.start())
    depth = 0
    for index in range(brace, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[match.start() : index + 1]
    raise ValueError(f"unterminated function in T31 source: {name}")


def render_writers(t31_source):
    names = [
        "tisp_mdns_pack4",
        "tisp_mdns_div_round_up",
        "tisp_mdns_y_3d_param_cfg",
        "tisp_mdns_y_2d_param_cfg",
        "tisp_mdns_c_3d_param_cfg",
        "tisp_mdns_c_2d_param_cfg",
    ]
    output = "\n\n".join(extract_c_function(t31_source, name) for name in names)
    replacements = {
        "tisp_mdns_pack4": "regtrace_t23_mdns_pack4",
        "tisp_mdns_div_round_up": "regtrace_t23_mdns_div_round_up",
        "tisp_mdns_y_3d_param_cfg": "regtrace_t23_mdns_y_3d_param_cfg",
        "tisp_mdns_y_2d_param_cfg": "regtrace_t23_mdns_y_2d_param_cfg",
        "tisp_mdns_c_3d_param_cfg": "regtrace_t23_mdns_c_3d_param_cfg",
        "tisp_mdns_c_2d_param_cfg": "regtrace_t23_mdns_c_2d_param_cfg",
        "mdns_frame_width": "regtrace_t23_mdns_frame_width",
        "mdns_frame_height": "regtrace_t23_mdns_frame_height",
        "mdns_y_ass_wei_adj_value1_intp_scalar": "mdns_y_ass_wei_adj_value1_intp",
        "mdns_c_false_edg_thres1_intp_scalar": "mdns_c_false_edg_thres1_intp",
    }
    for old, new in replacements.items():
        output = re.sub(rf"\b{old}\b", new, output)
    return "/* Generated from the checked-in T31 MDNS source reference. */\n" + output + "\n"


def main():
    args = parse_args()
    params = cache_text(args.mcp_cache, PARAMS_KEY)
    interpolation = cache_text(args.mcp_cache, INTP_KEY)
    destinations = parse_destinations(params)
    disassembly = function_disassembly(
        args.objdump, args.original_ko, "tiziano_mdns_params_refresh"
    )
    offsets = parse_tparams_offsets(disassembly)

    args.layout_output.write_text(render_layout(destinations, offsets))
    args.interpolation_output.write_text(
        render_interpolation(parse_interpolation(interpolation))
    )
    if bool(args.t31_source) != bool(args.writers_output):
        raise ValueError("--t31-source and --writers-output must be used together")
    if args.t31_source:
        args.writers_output.write_text(render_writers(args.t31_source.read_text()))


if __name__ == "__main__":
    main()
