#!/usr/bin/env python3
"""Generate the exact T23 SC2336 CLM startup register image."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


TUNING_HEADER_SIZE = 0x18
CLM_H_A_OFFSET = 0x11214
CLM_S_A_OFFSET = 0x1162E
CLM_H_T_OFFSET = 0x11E62
CLM_S_T_OFFSET = 0x1227C
CLM_H_D_OFFSET = 0x12AB0
CLM_S_D_OFFSET = 0x12ECA
CLM_CT_LIST_OFFSET = 0x13700
CLM_LUT_SHIFT_OFFSET = 0x1370C
CLM_H_SIZE = 1050
CLM_S_VALUES = 1050
CLM_STARTUP_CT = 5000


def read_bytes(blob: bytes, parameter_offset: int, count: int) -> bytes:
    start = TUNING_HEADER_SIZE + parameter_offset
    return blob[start : start + count]


def read_words(blob: bytes, parameter_offset: int, count: int) -> tuple[int, ...]:
    return struct.unpack_from(
        f"<{count}I", blob, TUNING_HEADER_SIZE + parameter_offset
    )


def read_saturation(blob: bytes, parameter_offset: int) -> tuple[int, ...]:
    return struct.unpack_from(
        f"<{CLM_S_VALUES}H", blob, TUNING_HEADER_SIZE + parameter_offset
    )


def select_profile(
    ct: int, ct_list: tuple[int, int, int]
) -> tuple[str, int, int]:
    a_ct, t_ct, d_ct = ct_list
    if ct <= a_ct + 200:
        return "A", CLM_H_A_OFFSET, CLM_S_A_OFFSET
    if ct < t_ct - 200:
        raise ValueError("startup CT unexpectedly requires A/T interpolation")
    if ct <= t_ct + 200:
        return "T", CLM_H_T_OFFSET, CLM_S_T_OFFSET
    if ct < d_ct - 200:
        raise ValueError("startup CT unexpectedly requires T/D interpolation")
    return "D", CLM_H_D_OFFSET, CLM_S_D_OFFSET


def pack_luts(hue: bytes, saturation: tuple[int, ...]) -> tuple[list[int], list[int]]:
    if len(hue) != CLM_H_SIZE or len(saturation) != CLM_S_VALUES:
        raise ValueError("invalid CLM LUT dimensions")

    hue_registers: list[int] = []
    saturation_registers: list[int] = []
    for row in range(30):
        row_base = row * 35
        for group in range(7):
            base = row_base + group * 5
            h0, h1, h2, h3, h4 = hue[base : base + 5]
            s0, s1, s2, s3, s4 = saturation[base : base + 5]

            saturation_registers.append(
                ((s3 & 0x1F) << 27)
                | ((s2 & 0x1FF) << 18)
                | ((s1 & 0x1FF) << 9)
                | (s0 & 0x1FF)
            )
            saturation_registers.append(
                ((s4 & 0x1FF) << 4) | ((s3 & 0x1E0) >> 5)
            )
            hue_registers.append(
                ((h4 & 0x0F) << 28)
                | ((h3 & 0x7F) << 21)
                | ((h2 & 0x7F) << 14)
                | ((h1 & 0x7F) << 7)
                | (h0 & 0x7F)
            )
            hue_registers.append((h4 & 0x70) >> 4)

    return hue_registers, saturation_registers


def render_array(name: str, values: list[int]) -> list[str]:
    if not any(values):
        return [f"static const uint32_t {name}[{len(values)}] = {{ 0U }};"]

    lines = [f"static const uint32_t {name}[] = {{"]
    for index in range(0, len(values), 6):
        chunk = values[index : index + 6]
        lines.append("    " + " ".join(f"0x{value:08x}U," for value in chunk))
    lines.append("};")
    return lines


def render(path: Path) -> str:
    blob = path.read_bytes()
    ct_list = read_words(blob, CLM_CT_LIST_OFFSET, 3)
    profile, hue_offset, saturation_offset = select_profile(
        CLM_STARTUP_CT, ct_list
    )
    hue = read_bytes(blob, hue_offset, CLM_H_SIZE)
    saturation = read_saturation(blob, saturation_offset)
    hue_registers, saturation_registers = pack_luts(hue, saturation)
    lut_shift = read_words(blob, CLM_LUT_SHIFT_OFFSET, 1)[0]

    lines = [
        "/* Generated by tools/t23_clm_image.py. */",
        f"/* Source tuning SHA256: {hashlib.sha256(blob).hexdigest()} */",
        (
            f"/* OEM startup CT {CLM_STARTUP_CT} selects the {profile} CLM LUT; "
            f"CT anchors are {ct_list[0]}/{ct_list[1]}/{ct_list[2]}. */"
        ),
        f"#define REGTRACE_T23_CLM_SC2336_LUT_SHIFT 0x{lut_shift:08x}U",
    ]
    lines.extend(render_array("regtrace_t23_clm_sc2336_h", hue_registers))
    lines.extend(render_array("regtrace_t23_clm_sc2336_s", saturation_registers))
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
