#!/usr/bin/env python3
"""Generate the exact T23 static AWB startup image from a sensor tuning blob."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


TUNING_HEADER_SIZE = 0x18
AWB_POINT_POS_OFFSET = 0x10D0
AWB_MF_PARA_OFFSET = 0x10E0
AWB_WB_STATIC_OFFSET = 0x110C


def read_u32(blob: bytes, parameter_offset: int) -> int:
    file_offset = TUNING_HEADER_SIZE + parameter_offset
    return struct.unpack_from("<I", blob, file_offset)[0]


def awb_register_value(point_pos: int, multiplier: int, base: int) -> int:
    if point_pos == 0 or point_pos >= 32:
        raise ValueError(f"unsupported AWB point position {point_pos}")
    gain = (multiplier * base + (1 << (point_pos - 1))) >> point_pos
    return 0x04000000 | min(gain << 2, 0x3FFF)


def render(path: Path) -> str:
    blob = path.read_bytes()
    point_pos = read_u32(blob, AWB_POINT_POS_OFFSET)
    mf_gr = read_u32(blob, AWB_MF_PARA_OFFSET + 0x10)
    mf_gb = read_u32(blob, AWB_MF_PARA_OFFSET + 0x14)
    base_gr = read_u32(blob, AWB_WB_STATIC_OFFSET)
    base_gb = read_u32(blob, AWB_WB_STATIC_OFFSET + 4)
    reg_gr = awb_register_value(point_pos, mf_gr, base_gr)
    reg_gb = awb_register_value(point_pos, mf_gb, base_gb)

    return f"""/* Generated by tools/t23_awb_static_image.py. */
/* Source tuning SHA256: {hashlib.sha256(blob).hexdigest()} */
#define REGTRACE_T23_AWB_SC2336_POINT_POS {point_pos}U
#define REGTRACE_T23_AWB_SC2336_MF_GR {mf_gr}U
#define REGTRACE_T23_AWB_SC2336_MF_GB {mf_gb}U
#define REGTRACE_T23_AWB_SC2336_BASE_GR {base_gr}U
#define REGTRACE_T23_AWB_SC2336_BASE_GB {base_gb}U
#define REGTRACE_T23_AWB_SC2336_REG_GR 0x{reg_gr:08x}U
#define REGTRACE_T23_AWB_SC2336_REG_GB 0x{reg_gb:08x}U
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("tuning_blob", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    output = render(args.tuning_blob)
    if args.output:
        args.output.write_text(output, encoding="ascii")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
