[sensor]
fps = 25

[stream0]
width = 2560
height = 1440
fps = 25
codec = h264
bitrate = 3000000
nr_vbs = 3

[stream1]
enabled = false
width = 640
height = 360
fps = 25
codec = h264
bitrate = 1000000
nr_vbs = 2

[jpeg]
enabled = false

[ring]
refmode = true

[osd]
enabled = false

[log]
level = debug
target = syslog
