tx_isp_t23_recovered-objs := tx_isp_t23_core.o \
			     tx_isp_t23_math.o \
			     tx_isp_t23_sinfo.o \
			     tx_isp_t23_mode.o \
			     tx_isp_t23_callback_plan.o \
			     tx_isp_t23_reg_profile.o \
			     tx_isp_t23_frame_layout.o \
			     tx_isp_t23_scaler.o \
			     tx_isp_t23_tuning_abi.o
obj-m += tx_isp_t23_recovered.o

ccflags-y += -I$(src)/../include
ccflags-y += -DREGTRACE_KERNEL_TREE_BUILD
ccflags-y += -std=gnu99
ccflags-y += -w
ccflags-y += -Wno-error=strict-prototypes
ccflags-y += -Wno-error=implicit-function-declaration
ccflags-y += -Wno-error=int-conversion
ccflags-y += -Wno-error=incompatible-pointer-types
